module.exports.descriptors = [
  'Forest',
  'Ancient',
  'Petrified',
  'Roaring',
  'Cascade',
  'Tumbling',
  'Silent',
  'Redwood',
  'Bullfrog',
  'Maple',
  'Misty',
  'Elk',
  'Grizzly',
  'Ocean',
  'Sea',
  'Sky',
  'Dusty',
  'Diamond'
];

module.exports.places = [
  'Flats',
  'Village',
  'Canyon',
  'Pond',
  'Group Camp',
  'Horse Camp',
  'Ghost Town',
  'Camp',
  'Dispersed Camp',
  'Backcountry',
  'River',
  'Creek',
  'Creekside',
  'Bay',
  'Spring',
  'Bayshore',
  'Sands',
  'Mule Camp',
  'Hunting Camp',
  'Cliffs',
  'Hollow'
];

module.exports.reviews = [
  'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  'Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.',
  'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  'Duis tempus enim non ante facilisis congue.',
  'Nunc imperdiet ut enim porttitor laoreet.',
  'Cras tincidunt, ligula vel pellentesque gravida, urna nunc aliquam sem, sed mollis ipsum enim sit amet arcu.',
  'Ut venenatis posuere libero accumsan malesuada.',
  'Praesent venenatis cursus velit vel malesuada.',
  'Nam iaculis mauris in massa sollicitudin sagittis.',
  'Vivamus ac nunc rhoncus, efficitur sem et, ornare mauris.'
];
